---
AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
Metrics:
  Enabled: false
Naming/HeredocDelimiterNaming:
  ForbiddenDelimiters:
  - END, EOD, EOF
Naming/FileName:
  Regex: !ruby/regexp /^[\w\@\-\+\.]+(\.rb)?$/
Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line
Layout/LineLength:
  Max: 118
  AllowedPatterns:
  # - "#: "
  # - ' url "'
  # - ' mirror "'
  # - " plist_options "
  # - ' executable: "'
  # - ' font "'
  # - ' homepage "'
  # - ' name "'
  # - ' pkg "'
  # - ' pkgutil: "'
  # - "    sha256 cellar: "
  # - "    sha256  "
  # - "#{language}"
  # - "#{version."
  # - ' "/Library/Application Support/'
  # - "\"/Library/Caches/"
  # - "\"/Library/PreferencePanes/"
  # - ' "~/Library/Application Support/'
  # - "\"~/Library/Caches/"
  # - "\"~/Library/Containers"
  # - "\"~/Application Support"
  # - " was verified as official when first introduced to the cask"
Layout/SpaceAroundOperators:
  Enabled: false
Style/Documentation:
  Exclude:
  - "**/{Formula,Casks}/**/*.rb"
Style/FrozenStringLiteralComment:
  EnforcedStyle: always
  Exclude:
  - "**/{Formula,Casks}/**/*.rb"
Style/StringConcatenation:
  Exclude:
  - "**/{Formula,Casks}/**/*.rb"
Style/FetchEnvVar:
  Exclude:
  - "**/Formula/**/*.rb"
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

