---

# TODO: ipatch, 
# 1. attempt to download the current bottle from the homebrew-freecad repo
# 1a. start with downloading swig@4.1.1 bottle,
# 1b. how to read deps used to build bottle
# 2. get a list of build and runtime deps for current bottle
# 3. check those deps against the current upstream counter part
# 4. if either a build time or runtime dep has been updated attempt rebuild the bottle
# 5. currently homebrew taps have the below workflow for updating bottles.
# 5a. create a new fork/branch make changes to single formula file
# 5b. submit PR to upstream repo
# 5c. label PR with pr-pull, cross fingers 🤞 and hope that a new bottle will be built.
# 6. notify maintainer of workflow run / updates

name: auto update bottles

on:
  # NOTE: run this action on request from github web UI
  workflow_dispatch:
  schedule:
    # min hour day month day-of-week,1-6 contrab.guru
    - cron: '1 4 */12 * *' # run task every 12 days

jobs:
  autoupdate-bottles:

    # a fast booting github-hosted runner
    runs-on: ubuntu-latest

    env:
      vmmojave:   192.168.1.114
      vmcatalina: 192.168.1.115
      vmbigsur:   191.168.1.116
      maintainer_emai: chris.r.jones.1983@gmail.com

    steps:

      - name: Configure SSH for github hosted runner
        id: configure_ssh
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/shrunserver.key
          chmod 600 ~/.ssh/shrunserver.key
          cat >>~/.ssh/config <<END
          Host shrunserver
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/shrunserver.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.ARCHBOX_SERVER_USER }}
          SSH_KEY: ${{ secrets.ACTIONS_SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.ARCHBOX_SERVER_IP }}
    
      - name: Debug runner IPs
        id: debug_runner_ips
        run: |
          echo "vmmojave: $vmmojave"
          echo "vmcatalina: $vmcatalina"
          echo "vmbigsur: $vmbigsur"

      - name: test_runner_status
        id: test_runner_status
        run: |
          for runner in "vmmojave" "vmcatalina" "vmbigsur"; do

            # Access the IP address using indirect expansion
            runner_ip="${!runner}"

            echo "$runner_ip"

            status_selfhosted_runner=$(curl -s -H "Authorization: Bearer ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}" \
            https://api.github.com/repos/freecad/homebrew-freecad/actions/runners \
            | jq -r ".runners[] | select(.name == \"$runner\") | .status // \"not found\"")

            echo "$runner is $status_selfhosted_runner"

          done

      - name: Print vm_status variable
        id: print_vm_status
        run: |
          echo "vmmojave status is ${{ env.vmmojave_status }}"
          echo "vmcatalina status is ${{ env.vmcatalina_status }}"
          echo "vmbigsur status is ${{ env.vmbigsur_status }}"

      - name: Send email on failure to reach runner service
        id: send_alert_email
        if: ${{ 
          env.vmmojave_status == 'down' || 
          env.vmcatalina_status == 'down' || 
          env.vmbigsur_status == 'down' 
          }}        
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: 'auto update bottle action results'
          from: ${{ secrets.SMTP_USERNAME }}
          to: ${{ env.maintainer_emai }}
          body: >
            scaffold out email message to let maintainer know a bottle artifact has changed,
            or an attempt to change a bottle artifact was made

