name: CI

on:
  pull_request_target:
  push:
    branches: [master, ipatch.exp.with.github.actions]

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_GITHUB_ACTIONS: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  GITHUB_ACTIONS_HOMEBREW_SELF_HOSTED: 1

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        os: [ macos-10.14, self-hosted ]
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    env:
      PATH: '/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin'
      HOMEBREW_DEVELOPER: 1
      GITHUB_ACTIONS_HOMEBREW_SELF_HOSTED: 1
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:

      - name: Checks out ipatch/homebrew-freecad fork `ci.yml`
        if: github.event.push.repo.full_name == github.repository
        # if: github.event_name == 'push' && steps.setup.outputs.has_token == 'true'
        uses: actions/checkout@v2
        # NOTE: workaround for missing secret in fork PRs - see https://github.com/actions/checkout/issues/298
        # NOTE: see https://github.com/rectorphp/rector/commit/d395e1c28b8e6a56711dcc2e10490a82965850e4
        with:
          repository: ipatch/homebrew-freecad
          ref: refs/heads/master
          fetch-depth: 0
          # token: "${{ secrets.IPATCH_PAT }} || github.token || ${{ secrets.GITHUB_TOKEN }}"

      - name: Set up Homebrew `ci.yml`
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          # repository: ipatch/homebrew-freecad
          # ref: refs/heads/master
          # fetch-depth: 0
          # token: "${{ secrets.IPATCH_PAT }} || github.token || ${{ secrets.GITHUB_TOKEN }}"


      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install Homebrew Bundler RubyGems
        if: steps.cache.outputs.cache-hit != 'true'
        run: brew install-bundler-gems

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup

      - run: brew test-bot --only-tap-syntax

      - run: brew test-bot --only-formulae
        if: github.event_name == 'pull_request'

      - name: Upload bottles as artifact
        if: always() && github.event_name == 'pull_request'
        uses: actions/upload-artifact@master
        with:
          name: bottles
          path: "*.bottle.*"
