name: brew pr-pull

on:
  pull_request_target:
    types:
      - labeled

env:
  # TODO: how to setup api token for CI/CD
  HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PULL_REQUEST: ${{ github.event.pull_request.number }}
  BRANCH: ${{ github.event.pull_request.head.ref }}
  #
  HOMEBREW_NO_ANALYTICS: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_NO_INSTALL_CLEANUP: 1

jobs:
  pr-pull:
    if: contains(github.event.pull_request.labels.*.name, 'pr-pull')
    # runs-on: macos-latest
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # token: "${{ secrets.OSX_CROSS_AVR_HOMEBREW_GITHUB_API_TOKEN }}"
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install Homebrew Bundler RubyGems
        if: steps.cache.outputs.cache-hit != 'true'
        run: brew install-bundler-gems

      - name: Set up git
        run: |
          git config --global user.name "ipatch"
          git config --global user.email "chris.r.jones.1983@gmail.com"

      - name: Pull bottles
        run: brew pr-pull --debug --tap=$GITHUB_REPOSITORY $PULL_REQUEST

      - name: Push commits
        uses: Homebrew/actions/git-try-push@master
        with:
          # token: ${{ secrets.OSX_CROSS_AVR_HOMEBREW_GITHUB_API_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: master

      - name: Delete branch
        if: github.event.pull_request.head.repo.fork == false
        run: git push --delete origin $BRANCH
